<Project>
  <PropertyGroup>
    <UnclaimableVersion>0.1.0</UnclaimableVersion>

    <Authors>ImtehQ</Authors>
    <Copyright>Copyright (c) 2026 Perry3D.nl</Copyright>
    <RepositoryUrl>https://github.com/ImtehQ/Unclaimable</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/ImtehQ/Unclaimable</PackageProjectUrl>
    <PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <DebugType>portable</DebugType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
